### ISSUE TITLE
Yêu cầu chức năng

### ISSUE THREAD

**Issue by lambmt** [lammonkey/ProjectSE_Appdulichao_Nhom17#7]

**Comment by Zoro1011** [comment]
Các yêu cầu chức năng:
1. Chức năng đăng ký:
- User thao tác:
+ Tại trang đăng nhập sẽ có mục đăng ký tài khoản. Người dùng chỉ cần chọn vào mục đó để tới trang đăng ký
+ Trang đăng ký tài khoản yêu cầu các thông tin như tên, email, số điện thoại, mật khẩu,.. để người dùng điền vào. 
- Hệ thống xử lý:
+ Khi nhập thông tin email hoặc số điện thoại thì sẽ được hệ thống kiểm tra xem đã từng sử dụng chưa, nếu chưa sẽ được đăng ký
+ Mỗi người sẽ có một tài khoản có ID riêng để hệ thống quản lý và ID sẽ được cung cấp sau khi tạo được tài khoản.

2. Chức năng đăng nhập:
- User thao tác:
+ Khi mở ứng dụng lên sẽ chuyển tới trang đăng nhập gồm Account và password để nhập thông tin đăng nhập.
- Hệ thống xử lý:
+ Khi nhập Account thì hệ thống sẽ kiểm tra email hoặc số điện thoại đã có trong dữ liệu hệ thống chưa. Sau đó sẽ kiểm tra mật khẩu đã nhập có trùng khớp vs tài khoản không.
+ Nếu nhập đúng sẽ đưa tới trang chủ để sử dụng ứng dụng. Nếu sai thì sẽ nhập lại hoặc phải đăng ký lại tài khoản.

3. Chức năng bản đồ:
- User thao tác:
+ Khi chọn mục bản đồ trên trang chủ thì nó sẽ cho phép bạn xem được bao quát bản đồ dưới dạng 2D, trong đó có chú thích các địa điểm có trải nghiệm 3D
- Hệ thống xử lý:
+ Bản đồ sẽ được lưu trữ sẵn nên khi chọn bản đồ sẽ tùy vào khu vực để trải nghiệm dưới dạng 2D hoặc 3D.

4. Chức năng lựa chọn địa điểm tham quan:
- User thao tác:
+ Khi chọn mục này, người dùng sẽ chọn những nội dung mình mong muốn như quốc gia, tỉnh, thành phố địa điểm cụ thể trong bản đồ.
- Hệ thống xử lý:
+ Sau khi chọn được các thông tin cần thiết thì hệ thống xử lý sẽ thể hiện rõ vị trí yêu cầu trên bản đồ.

5. Chức năng lựa chọn xem thực tế ảo:
- User thao tác:
+ Khi chọn mục này, tùy vào nhu cầu và thiết bị mà người dùng có thì khi chọn một địa điểm tham quan có trải nghiệm thực tế ảo. Người dùng sẽ được đưa tới 1 giao diện cho phép tương thích với các thiết bị trải nghiệm 3D như kính VR hoặc smartphone.
- Hệ thống xử lý:
+ Khi đã lựa chọn được thiết bị sử dụng thì người dùng sẽ được trải nghiệm địa điểm tham quan đó.

6. Chức năng đề xuất các địa điểm đang hot:
- User thao tác:
+ Trang chủ sẽ hiện thị các địa điểm nổi bật, người dùng có quyền chọn lựa vào những địa điểm gợi ý sẵn hoặc tìm kiếm một địa điểm khác theo nhu cầu của mình.
- Hệ thống xử lý:
+ Dựa vào các số liệu về việc lựa chọn địa điểm và đánh giá, thì hệ thống sẽ chọn ra những địa điểm được nhiều người yêu thích và đánh giá tốt nhất để đề xuất cho người dùng.

7. Chức năng video giới thiệu địa điểm tham quan:
- User thao tác:
+ Khi người dùng chọn một địa điểm nào đó, thì đi kèm với tính năng trải nghiệm 3D, người dùng có thể xem video giới thiệu của địa điểm đó.
- Hệ thống xử lý:
+ Những video sẽ được lưu sẵn trong dữ liệu nên khi chọn địa điểm nào đó thì video sẽ hiển thị kèm theo, người dùng có quyền lựa chọn xem hoặc bỏ qua.

8. Chức năng đánh giá tham quan:
- User thao tác:
+ Ở mỗi địa điểm sẽ có mục đánh giá sau trải nghiệm, người dùng có thể nhận xét ý kiến của mình trong đó và thể hiện số sao từ 1-5 sao mà mình nghĩ nó thích hợp.
- Hệ thống xử lý:
+ Mỗi nhận xét và số sao sẽ được lưu lại và hiển thị cho nhưng người tham quan sau biết được địa điểm đó như thế nào.
+ Nếu đánh giá tốt sẽ được yêu thích nhiều và trở thành địa điểm hot được đề xuất.
