### ISSUE TITLE
Yêu cầu phi chức năng

### ISSUE THREAD

**Issue by lambmt** [lammonkey/ProjectSE_Appdulichao_Nhom17#8]

**Comment by maidinhkhanh184** [comment]
1 Yêu cầu về sản phẩm: 
- Chỉ sử dụng tối đa 50mb bộ nhớ
- Giao diện người dùng thân thiện
- Tốc độ load app nhanh
- Hệ thống bảo mật tốt
- Khả năng bảo trì
- Tính thiết thực
-  Cho phép thông tin lưu hành, hoặc phân quyền người dùng
- Hệ thống sẽ cần năng lực tồn tại, chịu đựng các sự cố tự nhiên

2 Yêu cầu về tổ chức:
- Phương pháp thiết kế
- Ngôn ngữ lập trình:
-

3 Yêu cầu từ bên ngoài:
- Hệ thống không được để lộ thông tin khách hàng
- Chi phí phát triển: 100$
- Chi phí vận hành: 100$
- Thời gian hoàn thành: 4 tháng
-

**Comment by lambmt** [comment]
yêu cầu 50mb bộ nhớ có vẻ không khả thi, dữ liệu chủ yếu là video, hình ảnh nên tốn khá nhiều dung lượng rồi
